"""Independent full-population oracle of the SED reconstruction example.

Ported from the manuscript research reference (``validation/sed_reconstruction.py``
and ``validation/continuum_population.synch_f``, package b39cf0c). It uses
NumPy and SciPy only; from ``syncmoments`` it takes the physical constants
and nothing else (no response, basis, kernel or moment code), so the mock
data are not generated by the truncated design that is fitted.

Population (main.tex Appendix C.1). Latent coordinates ``(u, v, t)`` in
``[-1, 1]^3`` with ``gamma = gamma0 + s_gamma u``, ``B = B0 + s_B v`` and
``depth = depth0 + s_depth t``; the density is smooth, strictly positive and
correlated. Pitch angles are isotropic (``mu`` does not enter at
``L_mu = 0``). Conditional on ``(u, v, t)`` the viewing cosine ``eta`` has
density ``(1 + a P_2(eta))/2`` and the sky azimuth ``phi`` has density
``[1 + 2 Re(c exp(-2 i phi))]/(2 pi)``, so the angular averages are exact:
``<P_2(eta)> = a/5`` and ``<exp(2 i phi)> = c``. The finite angular family,
the compact energy segment and the absence of absorption, transfer,
calibration and excluded tails are declared assumptions of the example.

Units: frequencies in Hz, ``B`` in Gauss, depth in rad/m^2. ``direct_sed``
returns channel I, Q, U in units of ``NORM = sqrt(3) e^3 B0 / (4 pi m_e
c^2)`` (per unit source column); multiply by ``NORM`` for package units.
"""

from __future__ import annotations

import numpy as np
from numpy.polynomial.legendre import leggauss
from scipy.integrate import quad
from scipy.interpolate import CubicSpline
from scipy.special import kv

from syncmoments.constants import C_CGS, C_SI_M, E_ESU, M_E

GAMMA0, B0, DEPTH0 = 1e4, 5e-6, 2.0
SCALES = (2000.0, 1e-6, 0.3)
SUPPORT = {"gamma": (8000.0, 12000.0), "B": (4e-6, 6e-6), "depth": (1.7, 2.3)}
HALF_WIDTH = 0.04  # fractional channel half-width of the bump response
NORM = float(np.sqrt(3) * E_ESU**3 * B0 / (4 * np.pi * M_E * C_CGS**2))
F_GRID = (1e-4, 600.0, 6000)  # log-spline support and size of F(x)
F_ORACLE_TOL = 1e-7


def population(nodes):
    """``(z, w, a, c)`` on a ``nodes^3`` Gauss-Legendre grid in ``(u, v, t)``.

    ``z`` ``(n, n, n, 3)`` latent coordinates, ``w`` normalised weights,
    ``a`` the eta anisotropy in ``(0, 1)``, ``c`` the complex azimuth
    coefficient with ``|c| < 1/2`` (both densities strictly positive).
    """
    x, wx = leggauss(nodes)
    u, v, t = np.meshgrid(x, x, x, indexing="ij")
    measure = wx[:, None, None] * wx[None, :, None] * wx[None, None, :]
    rho = (1 + 0.2 * u) ** -2.6 * np.exp(
        0.25 * u - 0.15 * v + 0.2 * t + 0.55 * u * v - 0.4 * v * t + 0.3 * u * t
    )
    weights = measure * rho
    weights /= weights.sum()
    a = 0.5 + 0.2 * u - 0.15 * v + 0.1 * t
    c = 0.3 * np.exp(2j * (0.25 + 0.12 * u - 0.10 * v + 0.15 * t))
    if not (np.all((a > 0) & (a < 1)) and np.max(np.abs(c)) < 0.5):
        raise ValueError("the angular densities must stay positive")
    return np.stack([u, v, t], axis=-1), weights, a, c


def _rescaled(z, field_scale):
    """Latent coordinates after ``gamma -> gamma/sqrt(kappa)``, ``B -> kappa B``."""
    z = z.copy()
    gamma = (GAMMA0 + SCALES[0] * z[..., 0]) / np.sqrt(field_scale)
    field = (B0 + SCALES[1] * z[..., 1]) * field_scale
    z[..., 0] = (gamma - GAMMA0) / SCALES[0]
    z[..., 1] = (field - B0) / SCALES[1]
    return z


def moment_vector(entries, nodes=16, field_scale=1.0):
    """Closed-form angular averages of every slot ``(h, l, k, r, s, b, part)``.

    ``entries``: objects with ``h``, ``l``, ``k``, ``r``, ``s``, ``b`` and
    ``part`` (``"real"``, ``"re"`` or ``"im"``), in slot order; ``l`` must be
    0. The ``(u, v, t)`` average uses the same grid as ``population``; the
    angular averages ``a/5`` and ``c`` are exact. Dimensionless.
    """
    z, w, a, c = population(nodes)
    z = _rescaled(z, field_scale)
    out = []
    for e in entries:
        if e.l != 0:
            raise ValueError("the closed form covers L_mu = 0 only")
        if e.k > 2:
            raise ValueError("the closed form covers L_eta <= 2 only")
        # <P_k(eta)> under (1 + a P_2)/2: 1, 0, a/5 for k = 0, 1, 2
        angular = (1.0, 0.0 * a, a / 5)[e.k]
        value = np.sum(
            w
            * angular
            * np.prod(z ** np.array([e.r, e.s, e.b]), axis=-1)
            * (c if e.h == 2 else 1)
        )
        out.append(value.imag if e.part == "im" else value.real)
    return np.array(out)


def sample_grid(nodes=16, n_eta=3, n_phi=6):
    """Product grid for ``PopulationSamples``: ``(gamma, B, mu, eta, phi, depth, weights)``.

    ``n_eta``-node Gauss-Legendre in ``eta`` with weights ``(1 + a P_2)/2``
    (exact for the degree-4 integrands at ``n_eta >= 3``) and ``n_phi``
    uniform azimuths with weights ``[1 + 2 Re(c exp(-2 i phi))]/n_phi``
    (exact for ``|m| < n_phi``; the ``M2`` integrand reaches ``|m| = 4``).
    ``mu = 0``. Each array is ``(nodes^3 n_eta n_phi,)``.
    """
    z, w, a, c = population(nodes)
    eta, we = leggauss(n_eta)
    phi = 2 * np.pi * np.arange(n_phi) / n_phi
    p2 = (3 * eta**2 - 1) / 2
    w_eta = we[None, :] * (1 + a.reshape(-1, 1) * p2[None, :]) / 2
    ephi = np.exp(-2j * phi)
    w_phi = (1 + 2 * np.real(c.reshape(-1, 1) * ephi[None, :])) / n_phi
    weights = w.reshape(-1, 1, 1) * w_eta[:, :, None] * w_phi[:, None, :]
    shape = weights.shape
    zf = z.reshape(-1, 3)

    def spread(values):
        return np.broadcast_to(values.reshape(-1, 1, 1), shape).ravel()

    return {
        "gamma": spread(GAMMA0 + SCALES[0] * zf[:, 0]),
        "B": spread(B0 + SCALES[1] * zf[:, 1]),
        "mu": np.zeros(weights.size),
        "eta": np.broadcast_to(eta[None, :, None], shape).ravel(),
        "phi": np.broadcast_to(phi[None, None, :], shape).ravel(),
        "depth": spread(DEPTH0 + SCALES[2] * zf[:, 2]),
        "weights": weights.ravel(),
    }


def synch_f(x, nodes=96):
    """``F(x) = x int_x^inf K_{5/3}`` by ``x int_0^inf exp(-x cosh t) cosh(5t/3)/cosh t dt``.

    The ``t`` interval is truncated at 12 and integrated by ``nodes``-point
    Gauss-Legendre; the accuracy is checked by ``f_interpolator`` against an
    off-grid ``scipy.integrate.quad`` oracle.
    """
    x = np.asarray(x, dtype=float)
    if np.any(x <= 0):
        raise ValueError("synch_f needs positive x")
    zn, wn = leggauss(nodes)
    t, wt = 6 * (zn + 1), 6 * wn
    flat = x.reshape(-1)
    out = np.empty_like(flat)
    for start in range(0, flat.size, 4096):
        xx = flat[start : start + 4096, None]
        out[start : start + 4096] = xx[:, 0] * (
            np.exp(-xx * np.cosh(t)) @ (wt * np.cosh(5 * t / 3) / np.cosh(t))
        )
    return out.reshape(x.shape)


def f_interpolator():
    """``(evaluate, oracle_error)``: log-spline of ``synch_f`` checked off-grid to 1e-7."""
    lo, hi, n = F_GRID
    grid = np.geomspace(lo, hi, n)
    spline = CubicSpline(np.log(grid), np.log(synch_f(grid, 192)))

    def evaluate(x):
        x = np.asarray(x)
        if np.any((x < lo) | (x > hi)):
            raise ValueError("F interpolation support exceeded")
        return np.exp(spline(np.log(x)))

    checks = np.geomspace(0.02, 35, 47)
    oracle = np.array(
        [
            x * quad(lambda y: kv(5 / 3, y), x, np.inf, epsabs=1e-28, epsrel=3e-12)[0]
            for x in checks
        ]
    )
    error = float(np.max(np.abs(evaluate(checks) / oracle - 1)))
    if error >= F_ORACLE_TOL:
        raise AssertionError(f"F interpolation error {error:.3g} >= {F_ORACLE_TOL}")
    return evaluate, error


def _channel_weights(centres, n_nu):
    """Frequencies ``(n_centres, n_nu)`` and unit-integral bump weights ``(n_nu,)``."""
    xf, wf = leggauss(n_nu)
    nu = np.asarray(centres)[:, None] * (1 + HALF_WIDTH * xf)
    fw = wf * np.exp(1 - 1 / (1 - xf**2))
    return nu, fw / fw.sum()


def direct_sed(centres, f_eval, nodes=16, n_eta=96, n_nu=24, field_scale=1.0):
    """Channel ``(I, Q, U)`` ``(n_centres, 3)`` of the full population, in units of ``NORM``.

    Gauss quadrature in ``eta``; the conditional ``phi`` average is ``c``
    exactly; depth is integrated before the channel average. With
    ``field_scale = kappa`` the population is rescaled (``B -> kappa B``,
    ``gamma -> gamma/sqrt(kappa)``) and the source column divided by kappa.
    """
    z, w, a, c = population(nodes)
    nu, fw = _channel_weights(centres, n_nu)
    frequencies = nu.ravel()
    eta, ew = leggauss(n_eta)
    sine = np.sqrt(1 - eta**2)
    p2 = (3 * eta**2 - 1) / 2
    gamma = (GAMMA0 + SCALES[0] * z[:, :, 0, 0]).ravel() / np.sqrt(field_scale)
    field = (B0 + SCALES[1] * z[:, :, 0, 1]).ravel() * field_scale
    depth = DEPTH0 + SCALES[2] * z[..., 2]
    phase = np.exp(2j * (C_SI_M / frequencies) ** 2 * depth[..., None])
    wi = w.sum(axis=2).ravel()
    wia = (w * a).sum(axis=2).ravel()
    wp = (w[..., None] * c[..., None] * phase).sum(axis=2).reshape(-1, frequencies.size)
    wpa = (
        (w[..., None] * a[..., None] * c[..., None] * phase)
        .sum(axis=2)
        .reshape(-1, frequencies.size)
    )
    ii = np.zeros(frequencies.size)
    pp = np.zeros(frequencies.size, complex)
    for start in range(0, gamma.size, 6):
        sl = slice(start, start + 6)
        bp = field[sl, None] * sine
        critical = 3 * E_ESU * bp * gamma[sl, None] ** 2 / (4 * np.pi * M_E * C_CGS)
        x = frequencies[None, None, :] / critical[..., None]
        ki = bp[..., None] / B0 * f_eval(x)
        kq = -bp[..., None] / B0 * x * kv(2 / 3, x)
        i0 = np.einsum("a,ban->bn", ew / 2, ki)
        i2 = np.einsum("a,ban->bn", ew * p2 / 2, ki)
        q0 = np.einsum("a,ban->bn", ew / 2, kq)
        q2 = np.einsum("a,ban->bn", ew * p2 / 2, kq)
        ii += np.sum(wi[sl, None] * i0 + wia[sl, None] * i2, axis=0)
        pp += np.sum(wp[sl] * q0 + wpa[sl] * q2, axis=0)
    n_c = len(centres)
    ii = (ii.reshape(n_c, n_nu) @ fw) / field_scale
    pp = (pp.reshape(n_c, n_nu) @ fw) / field_scale
    return np.stack([ii, pp.real, pp.imag], axis=-1)


def rescaled_support(field_scale):
    """Support of the rescaled population (``gamma/sqrt(kappa)``, ``kappa B``)."""
    root = float(np.sqrt(field_scale))
    return {
        "gamma": [v / root for v in SUPPORT["gamma"]],
        "B": [v * field_scale for v in SUPPORT["B"]],
        "depth": list(SUPPORT["depth"]),
    }
